name: do-apps
region: fra
services:
- build_command: npm i && node ace build --production && cd build && npm ci
  environment_slug: node-js
  envs:
  - key: NODE_ENV
    scope: RUN_AND_BUILD_TIME
    value: production
  - key: APP_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:+42lT4GlhkFIbAtqBbHAfaVGHhcNz8sJ:3qM+yvver6UOj0Vz1r1jQivH1kT+DeFjPdj9GC4t5jXuMkgJObMmqme4GzHPTOj4]
  - key: HOST
    scope: RUN_AND_BUILD_TIME
    value: 0.0.0.0
  - key: PORT
    scope: RUN_AND_BUILD_TIME
    value: "8080"
  - key: SESSION_DRIVER
    scope: RUN_AND_BUILD_TIME
    value: cookie
  - key: CACHE_VIEWS
    scope: RUN_AND_BUILD_TIME
    value: "true"
  github:
    branch: master
    deploy_on_push: true
    repo: RomainLanz/do-apps
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: do-apps
  routes:
  - path: /
  run_command: node server.js
